DROP DATABASE IF EXISTS DuckDuckStore;
CREATE DATABASE DuckDuckStore;
USE DuckDuckStore;

CREATE TABLE utenti
(
    utente_ID      INT AUTO_INCREMENT PRIMARY KEY,
    nome           VARCHAR(25)    NOT NULL,
    cognome        VARCHAR(25)    NOT NULL,
    saldo          DECIMAL(10, 2) NOT NULL,
    email          VARCHAR(25)    NOT NULL,
    pass           VARCHAR(300)  NOT NULL,
    amministratore BOOLEAN        NOT NULL
);

CREATE TABLE prodotti
(
    prodotto_ID     INT AUTO_INCREMENT PRIMARY KEY,
    nome            VARCHAR(100)   NOT NULL,
    descrizione     VARCHAR(5000)   NOT NULL,
    prezzo          DECIMAL(10, 2) NOT NULL,
    quantita        int            NOT NULL,
    sconto          INT CHECK (sconto >= 0 AND sconto <= 100),
    categoria       ENUM('spaventose', 'natale', 'fantasy', 'professioni') NOT NULL,
    img             VARCHAR(1000)  NOT NULL,
    numero_acquisti INT DEFAULT 0
);

CREATE TABLE ordini
(
    ordine_ID  INT AUTO_INCREMENT PRIMARY KEY,
    prezzo_tot DECIMAL(10, 2) NOT NULL,
    data       DATE           NOT NULL,
    scontrino  JSON,
    utente_ID  INT,
    FOREIGN KEY (utente_ID) REFERENCES utenti (utente_ID)
);


INSERT INTO utenti (nome, cognome, saldo, email, pass, amministratore)
-- le password sono il solo nome il minuscolo, esempio: per Vito la password e' "vito"
VALUES  ('Vito', 'Altieri', 10000, 'vito@gmail.com',
        '9b592838e90a2adb1358c5496934792b0246de9dc230ab553d2622117884f3031c440a78ba579716401b862a27d6e5144b81208b15e829ea6aebe6d7c422a2e8',
        TRUE),
        ('Vittorio', "D'Alfonso", 10000, 'vittorio@gmail.com',
        'e0098f8bd8ade0638c23fb2f3ff534bca3ac87b9fa6367f5040ac77451d7fd75cf925ff1a799b0da9478ae9883f65fdf28638da94e02af542326c24789631229',
        TRUE),
        ('Matteo Ferdinando', 'Emolo', 10000, 'matteo@gmail.com',
        'c2ed182680410c5bf65559f2d005bf3262bddcffd8b1f3d69c20263af677f9be3eee013a8905d3f96245d177c1c1a5929d0c607cf2bf6e8eb5bbfa16bd0a4c3e',
        TRUE);

INSERT INTO prodotti (nome, descrizione, prezzo, quantita, sconto, categoria, img)
VALUES  ("Albero di Natale", "Christmas tree. Sicuramente non avetemai avuto un albero di Natale cosi carino. Un regalo da mettere sotto l'albero o una semplice decorazione", 15.0, 29, 15, 'natale',
        'https://milanduckstore.com/wp-content/uploads/2019/12/image0-360x360.png'),
        ("Angelo", "Guardian Angel White Rubber Duck. Acquista il protettore dell' affetto del Milan Duck Store. Con abito bianco, aureola gialla e ali bianche. Il nostro santo ospite per Natale.", 12.0, 27, 15, 'natale',
        'https://milanduckstore.com/wp-content/uploads/2019/04/guardian-no-littering-white-360x360.png'),
        ("Angelo Bianco", "Vuoi sentirti sempre protetto e amato? Questa paperella Angelo fa proprio al caso tuo!", 12.0, 15, 10, 'natale',
        'https://milanduckstore.com/wp-content/uploads/2020/02/6CA98F85-4C2F-49FD-B062-235B09596424-360x360.png'),
        ("Angelo Glitter", "L'angelo piu brillante sempre accanto a voi", 12.0, 47, 5, 'natale',
        'https://milanduckstore.com/wp-content/uploads/2023/11/Angeloglitter-360x360.png'),
        ("Babbo Natale", "Ma sogno o son desto??Un Babbo Natale a forma di paperetta? Ma certo, si tratta del Babba Natale del Milan Duck Store! Pronto per regalarti la felicita di una festa cosi magica...", 15.0, 72, 5, 'natale',
        'https://milanduckstore.com/wp-content/uploads/2019/05/santa-claus-360x360.png'),
        ("Christmas Jumper", "La nostra papera che indossa il maglione natalizio con la sciarpa bianca e rossa ed il cappello di Babbo Natale e pronta per il giorno di Natale!", 20.0, 20, 10, 'natale',
        'https://milanduckstore.com/wp-content/uploads/2019/12/image01-360x360.png'),
        ("Elfo di Natale", "questo Elfo ci aiutera a preparare tutti i regali!", 20.0, 29, 5, 'natale',
        'https://milanduckstore.com/wp-content/uploads/2024/05/Elfo-360x360.jpeg'),
        ("Giuseppe", "Il padre di Gesu con il bastone e la torcia conduira la Sua famiglia sulla via per Betlemme.", 12.0, 10, 15, 'natale',
        'https://milanduckstore.com/wp-content/uploads/2019/12/Giuseppe-360x360.png'),
        ("Glitter Red", "ecco come far scintillare ancora di piu il nostro Natale o la nostra stanza", 12.0, 90, 0, 'natale',
        'https://milanduckstore.com/wp-content/uploads/2023/08/glitterred-360x360.png'),
        ("Luminescente", "Questa papera si illumina al buio e ti terra compagnia fino all'alba...", 12.0, 53, 0, 'natale',
        'https://milanduckstore.com/wp-content/uploads/2021/07/lumin1-1-360x360.png'),
        ("Maria", "Maria con in braccio il piccolo Gesu, sara sicuramente al centro del Vostro presepe.", 12.0, 92, 15, 'natale',
        'https://milanduckstore.com/wp-content/uploads/2019/12/Maria-360x360.png'),
        ("Mini Babbo Natale Gomma Naturale", "Il piccolo Babbo Natale in gomma naturale e dipinto a mano Mdalle piccole dimensioni (3,5 x 3 x 3,5) ma pieno di doni per grandi e piccini.", 16.0, 83, 5, 'natale',
        'https://milanduckstore.com/wp-content/uploads/2020/12/image3-360x360.png'),
        ("Palla Natale Rossa", "Questa papera sara il miglior addobbo per il vostro albero di Natale!", 15.0, 58, 5, 'natale',
        'https://milanduckstore.com/wp-content/uploads/2023/07/pallanatale-360x360.png'),
        ("Palle di Natale, verdi", "La palla di natale a forma di paperetta del Milan Duck Store. Perfetta come regalo di Natale, da mettere sull'albero per impreziosire le festivita natalizie!", 12.0, 67, 0, 'natale',
        'https://milanduckstore.com/wp-content/uploads/2019/05/green-xmasball-360x360.png'),
        ("Papera Cappellino Natale", "Addobba il tuo Albero con questa dolcissima paperella", 15.0, 27, 10, 'natale',
        'https://milanduckstore.com/wp-content/uploads/2023/11/PallaCap-360x360.png'),
        ("Presepe", "Duck Nativity Scene, l'esclusivo ed originale presepe del Milan Duck Store, una super limited edition.", 90.0, 15, 15, 'natale',
        'https://milanduckstore.com/wp-content/uploads/2020/12/image0-360x360.png'),
        ("Pupazzo di neve", "Ma che splendido pupazzo di neve! Con il becco arancione, la sciarpa rossa ed il tipico cilindro sulla testa, e pronta per farti entrare nel clima del Natale!", 12.0, 61, 5, 'natale',
        'https://milanduckstore.com/wp-content/uploads/2019/05/snowman-360x360.png'),

        ("Black Star", "Black Star Rubber Duck.Compra il malvagio imperatore del Milan Duck Store. Dirige la Black Star, centro del lato oscuro. Che la forza sia con noi...", 12.0, 100, 15, 'spaventose',
        'https://milanduckstore.com/wp-content/uploads/2019/04/black-star-360x360.png'),
        ("Cyber Duck", "Cyber Rubber Duck.Compra il malvagio imperatore del Milan Duck Store. Dirige Cyber, il centro del lato oscuro. Che la forza sia con noi...", 12.0, 21, 15, 'spaventose',
        'https://milanduckstore.com/wp-content/uploads/2019/04/cyber-360x360.png'),
        ("Diavoletta", "Devil Woman Rubber Duck. Compra la peccaminosa diavolessa del Milan Duck Store. Ne ha un sacco nella manica. Ma non puoi resistere al fascino di questa papera malvagia con le ali rosse. Fa coppia perfetta con Devil Rubber Duck. Conosci una coppia cosi? Sorprendili con queste papere dall'inferno!", 12.0, 44, 10, 'spaventose',
        'https://milanduckstore.com/wp-content/uploads/2019/04/devil-woman-360x360.png'),
        ("Diavolo", "Devil Duck. Acquista la papera piu infuocata del Milan Duck Store. Da regalare ad amici e parenti che hanno il fuoco dentro di se...", 12.0, 50, 10, 'spaventose',
        'https://milanduckstore.com/wp-content/uploads/2019/04/devil-360x360.png'),
        ("Dracula", "Dracula Rubber Duck. Compra il conte assetato di sangue del Milan Duck Store. Questo principe delle tenebre spaventa a morte tutte le papere. Grande regalo di Halloween. O per regalarlo ad un amico che ha anche una vita notturna attiva!", 12.0, 58, 15, 'spaventose',
        'https://milanduckstore.com/wp-content/uploads/2019/04/dracula-1-360x360.png'),
        ("Drago", "il nostro drago dagli occhi smeraldo", 12.0, 47, 10, 'spaventose',
        'https://milanduckstore.com/wp-content/uploads/2022/10/drago-360x360.png'),
        ("Fantasma", "Ghost Rubber Duck. Acquista la papera spettrale del Milan Duck Store. Vestita di lenzuola bianche, spaventa tutte le anatre di notte. Da regalare a un amico che si spaventa facilmente al buio!", 12.0, 46, 15, 'spaventose',
        'https://milanduckstore.com/wp-content/uploads/2019/05/ghost-1-360x360.png'),
        ("Holdys Pipistrello", "Quale porta oggetti piu adatto per la festa di Halloween se non la nostra Holdys Bat?", 14.0, 73, 15, 'spaventose',
        'https://milanduckstore.com/wp-content/uploads/2022/10/holdysBat-360x360.jpeg'),
        ("Joker", "Non poteva mancare il pagliaccio piu malefico dei fumetti.", 12.0, 74, 0, 'spaventose',
        'https://milanduckstore.com/wp-content/uploads/2023/04/JokerA.jpeg-360x360.png'),
        ("Mostro Verde", "Green Monster Duck. Aspetta, non ho per caso visto questa papera nel film Monsters Inc.? A dispetto del suo corpo e dell'aspetto piuttosto insolito, dei denti appuntiti e dell'occhio gigante, questa papera e un compagno di bagnetto adorabile ed estremamente amichevole!", 12.0, 78, 15, 'spaventose',
        'https://milanduckstore.com/wp-content/uploads/2019/04/monster-green-360x360.png'),
        ("Papera nera con fiamme", "The Flame Rubber Duck. Acquista la papera che brucia come una torcia incandescente del Milan Duck Store. With burning flames and it looks like a floating open fire.", 12.0, 57, 15, 'spaventose',
        'https://milanduckstore.com/wp-content/uploads/2019/05/flame-360x360.png'),
        ("Paperelle con i i teschi", "Skull Rubber Duck. Sembra piu malvagio di quanto non lo sia: i teschi si anneriscono. Il suo corpo nero e cosparso di teschi bianchi, e comunque altamente adorabile. Vuole solo giocare con entrambi, giovani e vecchi. Per i pirati, che si imbarcano sulle vasche da bagno", 12.0, 73, 5, 'spaventose',
        'https://milanduckstore.com/wp-content/uploads/2019/04/duck-with-skulls-360x360.png'),
        ("Skull Horse", "Ma chi e che porta paura in tutto il vicinato? E forse un fantasma? Ma no, e la papera a forma di scheletro di cavallo...Sembra paurosa ma nella tua vaschetta da bagno si trasformera nella piu dolce tra le paperette!", 12.0, 64, 0, 'spaventose',
        'https://milanduckstore.com/wp-content/uploads/2019/05/skull-horse-360x360.png'),
        ("X-Ray", "X Ray Duck, la papera del Milan Duck Store che si e messa davvero a nudo per voi! Uno scheletro davvero carino, perfetto non solo per il bagnetto piu terrificante ma anche come regalo di Halloween...", 20.0, 92, 0, 'spaventose',
        'https://milanduckstore.com/wp-content/uploads/2019/05/luxury-xray-360x360.png'),

        ("Avatara Duck", "Avatara Duck. La nostra papera blu è pronta a vivere nel suo mondo fantastico meraviglioso.", 12.0, 31, 10, 'fantasy',
        'https://milanduckstore.com/wp-content/uploads/2019/10/RWSB9005-360x360.png'),
        ("Biancaneve", "Snow White Rubber Duck.Acquista la bella ragazza addormentata delle fiabe del Milan Duck Store. Con la sua tipica acconciatura, il cerchietto rosso ed il vestito blu da principessa, è il regalo perfetto per gli amanti delle fiabe della buona notte.", 12.0, 20, 15, 'fantasy',
        'https://milanduckstore.com/wp-content/uploads/2019/05/snow-white-360x360.png'),
        ("Black Star Glitter", "ora brillerà ancora di più nello spazio", 12.0, 67, 0, 'fantasy',
        'https://milanduckstore.com/wp-content/uploads/2023/11/darkglitter-360x360.png'),
        ("Catwoman", "La più perfida gattina dei fumetti è arrivata al Milan Duck Store", 12.0, 59, 15, 'fantasy',
        'https://milanduckstore.com/wp-content/uploads/2023/04/Catwoman-360x360.png'),
        ("Coniglietta", "Bunny Rubber Duck. Acquista la papera dal cuore pieno di amore del Milan Duck Store. Con il suo fascino e bellezza, è irresistibile per tutti!", 12.0, 56, 0, 'fantasy',
        'https://milanduckstore.com/wp-content/uploads/2019/04/bunny-1-360x360.png'),
        ("Fatina", "Fairy Duck la fatina porta fortuna del Milan Duck Store.", 12.0, 20, 0, 'fantasy',
        'https://milanduckstore.com/wp-content/uploads/2019/10/MOEF1591-1-360x360.png'),
        ("Fatina dei denti", "Tooth Fairy Duck. La nostra fatina dei denti porterà tanta gioia ai vostri bimbi.", 12.0, 58, 15, 'fantasy',
        'https://milanduckstore.com/wp-content/uploads/2021/11/fatina-1-360x360.png'),
        ("Glitter Unicorn", "Entra nel magico mondo fatato a cavallo di un dolce unicorno glitterato.. incontrerai fate, folletti, principi e regine.", 12.0, 48, 0, 'fantasy',
        'https://milanduckstore.com/wp-content/uploads/2023/06/glitterunicorn-360x360.jpeg'),
        ("Holdys Unicorno", "Holdys Unicorn. Mai più disordine e caos in casa . Il nostro unicorno Holdys è un deposito di spazzolini/penne super fiabesco. Quindi fai attenzione agli amanti degli unicorni. Ecco un nuovo pezzo per la tua collezione.", 14.0, 68, 15, 'fantasy',
        'https://milanduckstore.com/wp-content/uploads/2019/04/holdys-unicorn-white-360x360.png'),
        ("M Duck", "M Rubber Duck. Compra questa strana creatura del Milan Duck Store. Sta per affrontare nuove avventure e mettersi nei guai … proprio da Minion", 12.0, 60, 5, 'fantasy',
        'https://milanduckstore.com/wp-content/uploads/2019/04/m_duck-1-360x360.png'),
        ("Mini Unicorno Bianco", "Mini Unicorn White. Più piccolo e più carino: i piccoli unicorni bianchi sono irresistibili e assolutamente adorabili. Un pezzo di magia in movimento!
        Dolce incantevole", 7.0, 60, 0, 'fantasy',
        'https://milanduckstore.com/wp-content/uploads/2019/04/mini-unicorn-white-360x360.png'),
        ("Mini Unicorno, rosa", "Mini Unicorn Rubber Duck. Compra la creatura leggendaria del Milan Duck Store. In versione “mini” rosa con capelli viola e corno giallo.", 7.0, 39, 0, 'fantasy',
        'https://milanduckstore.com/wp-content/uploads/2019/05/mini-pink-unicorn-360x360.png'),
        ("Pantera Rosa", "Una papera… o una pantera rosa? Affascinante e di gran classe, è pronta a rubare il cuore a tutti gli amanti del colore rosa.. Perfetta anche come regalo per gli ispettori più scaltri e deduttivi della storia!", 12.0, 39, 5, 'fantasy',
        'https://milanduckstore.com/wp-content/uploads/2019/05/pinky-360x360.png'),
        ("Papera travestita da Unicorno", "La nostra paperella non vedeva l’ora di travestirsi da Unicorno", 12.0, 14, 5, 'fantasy',
        'https://milanduckstore.com/wp-content/uploads/2022/12/uniCostume-360x360.jpeg'),
        ("Pegaso", "Pegasus Rubber Duck. Il nostro Pegaso non è solo una figura di fantasia, puoi davvero toccarlo e portarlo a casa con te. Con questa papera di gomma per ogni amante delle creature magiche, un piccolo sogno diventa realtà. Le sue ali impressionanti e il corno unico sulla sua fronte lo fanno apparire davvero incantevole. Sta già pensando ad un posto altrettanto speciale nella sua nuova casa.", 12.0, 18, 0, 'fantasy',
        'https://milanduckstore.com/wp-content/uploads/2019/04/pegasus-1-360x360.png'),
        ("Pikachu", "Piku Rubber Duck. Acquista un eroe elettrico del Milan Duck Store. Sembra la famosa figura Pokémon. Con le guance rosse, il naso nero e le strisce sulla schiena.", 12.0, 63, 0, 'fantasy',
        'https://milanduckstore.com/wp-content/uploads/2019/04/piku-1-360x360.png'),
        ("Rainbow Duck", "Luxury Rainbow Duck. “Ma cosa si vede in fondo a quella vallata? E’ una papera o un arcobaleno?” Acquista la tua papera dai colori dell’arcobaleno, regalo perfetto per chi aspetta con ansia la fine di uno scroscio di pioggia per poter ammirare questi splendidi colori…", 20.0, 54, 0, 'fantasy',
        'https://milanduckstore.com/wp-content/uploads/2019/05/rainbow-duck-360x360.png'),
        ("Red Star Duck", "Red Star Duck. Il Super Eroe più forte che ci sia.", 12.0, 64, 5, 'fantasy',
        'https://milanduckstore.com/wp-content/uploads/2019/10/JAAB6256-360x360.png'),
        ("Sirenetta", "Mermaid Rubber Duck. Compra l’attrazione fatale del Milan Duck Store. Metà donna e metà pesce, è la misteriosa creatura marina che fa impazzire il marinaio.", 12.0, 80, 10, 'fantasy',
        'https://milanduckstore.com/wp-content/uploads/2019/04/mermaid-1-360x360.png'),
        ("Smiley", "Tante, tantissime faccine sorridenti per il nostra Smiley Duck del Milan Duck Store. Per portare gioa e sorrisi a chi più ne ha bisogno!", 20.0, 58, 15, 'fantasy',
        'https://milanduckstore.com/wp-content/uploads/2019/05/luxury-smiley-360x360.png'),
        ("Soldato Cibernetico", "Chi ci salverà in caso di attacco cibernetico? Chi veglierà su dinoi contro i terroristi del web? Non preoccupatevi, c’è il Cyber Soldier Duck del Milan Duck Store!", 12.0, 16, 5, 'fantasy',
        'https://milanduckstore.com/wp-content/uploads/2019/05/cyber-soldier-360x360.png'),
        ("Sonic", "In quanti abbiamo giocato a questo videogioco?! Finalmente è arrivato anche al Milan Duck Store.", 12.0, 70, 15, 'fantasy',
        'https://milanduckstore.com/wp-content/uploads/2023/08/sonic-360x360.png'),
        ("Star Magic", "“Ma che magia queste splendide stelle argentate!” Black Star Magic, la paperetta del Milan Duck Store per gli amanti della magia e di mondi incantati…", 20.0, 72, 5, 'fantasy',
        'https://milanduckstore.com/wp-content/uploads/2019/05/luxury-star-magic-360x360.png'),
        ("Star Popper", "Le paperelle stellari sono pronte all’azione! Ecco un cattivissimo Star Popper armato fino ai denti alla ricerca degli ultimi Jedi…", 12.0, 58, 0, 'fantasy',
        'https://milanduckstore.com/wp-content/uploads/2020/02/image0-1-360x360.png'),
        ("Thor", "Ma chi sta volando nel cielo del DuckStore con elmo, folta barba ed un martello gigante tenuto in mano?! Ma è il Thor del Milan DuckStore! Per chi sogna di vivere un giorno nella meravigliosa e lontana Asgard…", 12.0, 94, 10, 'fantasy',
        'https://milanduckstore.com/wp-content/uploads/2021/12/you4-360x360.png'),
        ("Unicorn Duck", "Glow in the Duck Unicorn . Acquista questa papera – unicorno che si illumina al contatto con l’acqua!", 18.0, 56, 5, 'fantasy',
        'https://milanduckstore.com/wp-content/uploads/2019/05/unicorn-360x360.png'),
        ("Unicorno bianco", "Unicorn Rubber Duck. Compra la creatura leggendaria del Milan Duck Store. In bianco con capelli viola e corno giallo.", 12.0, 63, 5, 'fantasy',
        'https://milanduckstore.com/wp-content/uploads/2019/05/unicorn-white-360x360.png'),
        ("Unicorno blu", "La papera Unicorno. Compra la papera Unicorno di colore blu del Milan Duck Store. Per gli amanti dei mondi fatati e degli animali fantastici!", 12.0, 40, 5, 'fantasy',
        'https://milanduckstore.com/wp-content/uploads/2019/05/unicorn-blu-360x360.png'),
        ("Unicorno rosa", "Unicorn Rubber Duck. Compra la creatura leggendaria del Milan Duck Store. In rosa con capelli viola e corno giallo.", 12.0, 50, 0, 'fantasy',
        'https://milanduckstore.com/wp-content/uploads/2019/04/unicorn-pink-360x360.png'),
        ("Unicorno viola", "La papera Unicorno. Compra la papera Unicorno di colore viola del Milan Duck Store. Per gli amanti dei mondi fatati e degli animali fantastici!", 12.0, 26, 5, 'fantasy',
        'https://milanduckstore.com/wp-content/uploads/2019/05/unicorn-purple-360x360.png'),
        ("Vedova Nera", "Dark Duck Woman. La nostra papera super eroe.", 12.0, 56, 0, 'fantasy',
        'https://milanduckstore.com/wp-content/uploads/2019/10/EISZ1727-360x360.png'),
        ("Yoda", "Il cavaliere Jedi di grande longevità che addestrerà tutte le nostre papere", 12.0, 63, 10, 'fantasy',
        'https://milanduckstore.com/wp-content/uploads/2023/04/babyyoda-360x360.png'),

        ("Al Capone", "Al Capo Rubber Duck.Compra la papera gangster del Milan Duck Store. Indossa occhiali da sole, abito nero e cappello. Fuma un sigaro… Fai attenzione a questo mafioso, ha una pistola ed è collegato al sindacato dei quaccheri …", 12.0, 91, 5, 'professioni',
        'https://milanduckstore.com/wp-content/uploads/2019/04/al-capo-360x360.png'),
        ("Arbitro", "Referee Rubber Duck. Fair play: la papera arbitro prende decisioni giuste: un bel regalo per i tifosi di calcio. Ma tieni a mente che l’arbitro non ha paura di mostrare il cartellino rosso. … tira il cartellino rosso in violazione delle regole.", 12.0, 93, 15, 'professioni',
        'https://milanduckstore.com/wp-content/uploads/2019/04/referee-360x360.png'),
        ("Artista", "Acqusita il papero artista del Milan Duck Store. Con la sua tovolozza di colori, le macchie di pittura ed il tipico cappello da pittore, tingerà di mille colori le tue giornate!", 12.0, 86, 15, 'professioni',
        'https://milanduckstore.com/wp-content/uploads/2019/05/artista-360x360.jpeg'),
        ("Avvocato", "Avete avuto problemi con la legge di recente? Allora è tempo di consultare la nostra paperella Avvocato!", 12.0, 49, 0, 'professioni',
        'https://milanduckstore.com/wp-content/uploads/2020/02/lawyer-360x360.png'),
        ("Ballerina", "Siete pronti a ballare e piroettare con la papera più leggiadra del Milan Duck Store?!", 12.0, 25, 15, 'professioni',
        'https://milanduckstore.com/wp-content/uploads/2021/02/ballerina1-360x360.png'),
        ("Ballerina di flamenco", "La papera che balla il flamenco del Milan Duck Store. Per gli amanti della musica e dei balli scatenati!", 12.0, 75, 0, 'professioni',
        'https://milanduckstore.com/wp-content/uploads/2019/05/flamenco-360x360.png'),
        ("Barista", "caffè, cappuccino, macchiato caldo, macchiato freddo, marocchino, il nostro barista saprà esaudire ogni vostra richiesta.", 12.0, 41, 15, 'professioni',
        'https://milanduckstore.com/wp-content/uploads/2024/05/barista-360x360.jpeg'),
        ("Barman", "Gradisci un cocktail? Un aperitivo? O anche solo una tonica con uno spicchio di limone? La papera Barista del Milan Duck Store è pronta per esaudire i tuoi desideri!", 12.0, 37, 0, 'professioni',
        'https://milanduckstore.com/wp-content/uploads/2021/02/barista1-360x360.png'),
        ("Bodybuilder", "Bodybuilder Rubber Duck. Acquista lo sportivo del Milan Duck Store. Solleva pesi mentre mostra i suoi addominali. Indossa pantaloncini rossi da allenamento.", 12.0, 93, 15, 'professioni',
        'https://milanduckstore.com/wp-content/uploads/2019/04/bodybuilder-1-360x360.png'),
        ("Business Man", "Business Man Rubber Duck. Acquista il deal maker del Milan Ducks Store. Con giacca e cravatta blu, occhiali e cartella. Il nostro papero d’affari è sempre molto impegnato a cercare nuove opportunità di business.", 12.0, 15, 10, 'professioni',
        'https://milanduckstore.com/wp-content/uploads/2019/04/business-man-360x360.png'),
        ("Business Woman", "Business Woman Rubber Duck.
        Acquista la miss money maker del Milan Ducks Store. Con vestito blu, occhiali e computer. La nostra papera di gomma d’affari è sempre molto impegnata a fare telefonate per generare business!", 12.0, 62, 0, 'professioni',
        'https://milanduckstore.com/wp-content/uploads/2019/04/business-woman-360x360.png'),
        ("Cacciatore", "Hunter Rubber Duck. Non importa quanto piccola possa sembrare questa anatra di gomma, insieme al suo compagno fedele raggiunge sempre il suo obiettivo. Attraverso il suo binocolo ha gli occhi come un’aquila e vede attraverso anche la foresta più verde, dove può camuffarsi meravigliosamente grazie al vestito. Il suo fucile è sempre a portata di mano. Questo cacciatore è ben preparato. Quindi comincia la caccia!", 12.0, 13, 5, 'professioni',
        'https://milanduckstore.com/wp-content/uploads/2019/04/hunter-1-360x360.png'),
        ("Calciatore", "La papera calciatrice. Compra la papera a forma di calciatore del Milan Duck Store. E’ pronta per fare gol ai suoi avversari!", 12.0, 11, 10, 'professioni',
        'https://milanduckstore.com/wp-content/uploads/2019/05/soccer-360x360.png'),
        ("Capitano", "Captain Rubber Duck. Acquista la papera marittima del Milan Duck Store. Con mano ferma conduce le nostre papere attraverso la vasca da bagno. Non c’è un mare che non ha navigato o un oceano che non ha attraversato. Regalo perfetto per un amico che ama il mare.", 12.0, 78, 10, 'professioni',
        'https://milanduckstore.com/wp-content/uploads/2019/04/captain-1-360x360.png'),
        ("Capo Indiano", "Luxury Chief Duck. Acquista il coraggioso Capo Indiano del Milan Duck Store. Con il tradizionale copricapo ed i segni della sua tribù.", 20.0, 21, 10, 'professioni',
        'https://milanduckstore.com/wp-content/uploads/2019/05/deluxe-chief-360x360.png'),
        ("Chef", "Chef Rubber Duck. Acquista il premiato cuoco del Milan Duck Store. Un vero eroe della cucina. Ottimo regalo per amici gourmet.", 12.0, 18, 0, 'professioni',
        'https://milanduckstore.com/wp-content/uploads/2019/04/chef-1-360x360.png'),
        ("Chef Duck", "LuxuryChef Duck. Acquista il super chef del Milan Duck Store. Con la giacca da chef, è pronto per dettare le regole in cucina!", 20.0, 96, 15, 'professioni',
        'https://milanduckstore.com/wp-content/uploads/2019/05/deluxe-chef-360x360.png'),
        ("Chimico", "“Ma questa paperetta del Milan Duck Store sembra proprio uno scienziato pazzo…”Con intrugli di ogni colore e alambicchi a portata di mano, è pronta per un nuovo strano esperimento!", 12.0, 66, 0, 'professioni',
        'https://milanduckstore.com/wp-content/uploads/2019/05/chemist-360x360.png'),
        ("Chirurgo", "La papera chirurgo. Compra la paperella chirurgo del Milan Duck Store. Per gli amanti della medicina e… delle fiction sui camici verdi!", 12.0, 93, 15, 'professioni',
        'https://milanduckstore.com/wp-content/uploads/2019/05/surgeon-360x360.png'),
        ("Ciclista", "Cycling Rubber Duck. Acquista l’eroe del ciclismo del Duck Store di Milano. Con bicicletta e casco. Pronto a saltare e affrontare tutti i percorsi!", 12.0, 20, 0, 'professioni',
        'https://milanduckstore.com/wp-content/uploads/2019/04/cycling-1-360x360.png'),
        ("Clown", "Clown Rubber Duck. Compra il colorato clown del Milan Duck Store. Divertimento assicurato con questa papera di gomma allegra.", 12.0, 86, 15, 'professioni',
        'https://milanduckstore.com/wp-content/uploads/2019/04/clown-1-360x360.png'),
        ("Contadina", "Farmer Female Duck.
        Fuori in giardino! La papera contadina femmina è diligente e ha già raccolto alcune grandi mele lussureggianti. Chi ne vorrebbe una?", 12.0, 33, 10, 'professioni',
        'https://milanduckstore.com/wp-content/uploads/2019/04/farmer-woman-360x360.png'),
        ("Contadino", "Farmer Rubber Duck. Acquista il contadino del Milan Duck Store. Sulla strada per andare verso il suo campo con rastrello e secchio!", 12.0, 18, 10, 'professioni',
        'https://milanduckstore.com/wp-content/uploads/2019/04/farmer-1-360x360.png'),
        ("Corridore", "Anche il nostro runner si sta preparando per la maratona!", 12.0, 86, 5, 'professioni',
        'https://milanduckstore.com/wp-content/uploads/2022/12/runner-360x360.jpeg'),
        ("Cowboy Duck", "Luxury Cowboy Duck. Acquista l’eroe delle lontane praterie del Milan Duck Store. Con la sua tipica bandana ed il cappello da cowboy. Pronto per cavalcare verso sperduti orizzonti.", 20.0, 83, 10, 'professioni',
        'https://milanduckstore.com/wp-content/uploads/2019/05/deluxe-cowboy-360x360.png'),
        ("Dentista", "Dentist Rubber Duck. Acquista il mago dei denti del Milan Duck Store. Non aver paura! Questa speciale papera mantiene i tuoi denti sani e belli. Un bel regalo per il tuo dentista!", 12.0, 12, 5, 'professioni',
        'https://milanduckstore.com/wp-content/uploads/2019/04/dentist-1-360x360.png'),
        ("Detective", "Detective Rubber Duck. Acquista l’elegante ed investigativa paperella del Milan Duck Store. Con cappello, tubo e lente di ingrandimento. Regalo perfetto per un amico molto intelligente.", 12.0, 38, 0, 'professioni',
        'https://milanduckstore.com/wp-content/uploads/2019/04/detective-1-360x360.png'),
        ("DJ", "Chi sta suonando questa musica meravigliosa?Si tratta di una paperetta? Ma è il famoso DJ del Milan Duck Store!", 12.0, 68, 0, 'professioni',
        'https://milanduckstore.com/wp-content/uploads/2019/05/dj-360x360.png'),
        ("Dj Duck", "Luxury Dj Duck. “Suoniamo un po’ di musica insieme!” Deluxe Dj Duck sa sempre come animare una festa.", 20.0, 53, 0, 'professioni',
        'https://milanduckstore.com/wp-content/uploads/2019/05/deluxe-djduck-360x360.png'),
        ("Dottore", "Doctor Rubber Duck Man. Compra il genio della medicina del Milan Duck Store. È sempre lì se hai bisogno di lui. Con il suo set di emergenza e lo stetoscopio sta andando a salvare un altro paziente. Sorprendi il tuo medico o amico paziente con questo sano regalo!", 12.0, 93, 10, 'professioni',
        'https://milanduckstore.com/wp-content/uploads/2019/04/emergency-doc-360x360.png'),
        ("Dottoressa", "Female Doctor Duck.Compra il genio della medicina del Milan Duck Store. È sempre lì se hai bisogno di lei. Con il suo set di emergenza e lo stetoscopio sta per salvare un altro paziente.", 12.0, 36, 10, 'professioni',
        'https://milanduckstore.com/wp-content/uploads/2019/04/doctor-female-360x360.png'),
        ("Fan", "La paperetta a forma di Fan del Milan Duck Store aspetta tutti coloro che si emozionano appena intravedono il proprio artista preferito! Per chi non perde occasione per chiedere un autografo o fare un selfie!", 12.0, 88, 15, 'professioni',
        'https://milanduckstore.com/wp-content/uploads/2019/05/fan-360x360.png'),
        ("Fantino", "Horse Rider Duck. Il nostro cavaliere è ben preparato per un bel giro nel bosco,equipaggiato con casco, frusta e il tipico abbigliamento da fantino! Grande regalo per gli amanti dei cavalli!", 12.0, 81, 15, 'professioni',
        'https://milanduckstore.com/wp-content/uploads/2019/04/horse-rider-360x360.png'),
        ("Fotografo", "La paperella amante dei primi piani e del grandangolo, sempre alla ricerca dello scatto perfetto!", 12.0, 89, 15, 'professioni',
        'https://milanduckstore.com/wp-content/uploads/2020/02/image0-360x360.png'),
        ("Freud Psicologo", "Solo il nostro Freud saprà aiutarvi", 16.0, 75, 0, 'professioni',
        'https://milanduckstore.com/wp-content/uploads/2024/09/Freud-360x360.jpeg'),
        ("Gamer", "Tra giochi di ruolo, fantasy e spara tutto il vostro duck gamer non si staccherebbe mai dalla suo console", 12.0, 22, 5, 'professioni',
        'https://milanduckstore.com/wp-content/uploads/2022/08/gamer1-360x360.jpeg'),
        ("Gentiluomo", "Gentleman Duck. Con un ombrello ed un sacco di fascino: ​​questo signore non lascerebbe mai una bella signora papera sotto la pioggia! Con i suoi modi eccellenti è un vero arricchimento per ogni collezione di papere.", 12.0, 66, 15, 'professioni',
        'https://milanduckstore.com/wp-content/uploads/2019/04/gentleman-1-360x360.png'),
        ("Giudice", "Judge Duck. La nostra papera con grande responsabilità deciderà le sorti di molti.", 12.0, 38, 15, 'professioni',
        'https://milanduckstore.com/wp-content/uploads/2019/10/EYXF3836-360x360.png'),
        ("Hostess di volo", "Stewardess rubber duck. Acquista l’assistente di volo del Milan Duck Store. Allacciate le cinture di sicurezza per un viaggio intorno al mondo con i nostri assistenti. Sarà davvero un volo piacevole.", 12.0, 22, 5, 'professioni',
        'https://milanduckstore.com/wp-content/uploads/2019/04/stewardess-360x360.png'),
        ("I Love Pizza", "Ecco che I Love Pizza Duck si aggiunge all’esclusiva collezione del Duck Store!", 15.0, 88, 15, 'professioni',
        'https://milanduckstore.com/wp-content/uploads/2021/09/pizza-duck-1-360x360.png'),
        ("Idraulico", "Handyman Duck. Acquista la papera carpentiere del Milan Duck Store. Tra un martello ed un cacciavite, questa papera è sempre pronta a costruire qualcosa di solido e duraturo!", 12.0, 63, 15, 'professioni',
        'https://milanduckstore.com/wp-content/uploads/2019/04/handyman-1-360x360.png'),
        ("Imbianchino", "Painter Rubber Duck. Ama la pittura e le macchie colorate, trasformando qualsiasi superficie bianca in un’incredibile opera d’arte. Porta il colore a casa tua!", 12.0, 24, 5, 'professioni',
        'https://milanduckstore.com/wp-content/uploads/2019/04/painter-1-360x360.png'),
        ("Infermiera", "La papera infermiera del Milan Duck Store. Per tutti coloro che amano prendersi cura amorevolmente degli altri!", 12.0, 12, 0, 'professioni',
        'https://milanduckstore.com/wp-content/uploads/2019/05/nurse-360x360.png'),
        ("Influencer", "Sei sempre attenta alle nuove tendenze? Appena hai un secondo libero corri dai tuoi amati follower? La nostra Influencer Duck è la papera che fa per te!", 12.0, 15, 5, 'professioni',
        'https://milanduckstore.com/wp-content/uploads/2021/02/influencer2-360x360.png'),
        ("Informatico", "Ecco la papera che ti terrà per mano tra codici, programmi e tecnologia.", 12.0, 83, 0, 'professioni',
        'https://milanduckstore.com/wp-content/uploads/2022/08/itdeveloper-360x360.jpeg'),
        ("Ingegnere", "Engineer Rubber Duck. Acquista il costruttore del Milan Duck Store. Con casco, piani di costruzione, documenti contrattuali e tuta blu.", 12.0, 89, 10, 'professioni',
        'https://milanduckstore.com/wp-content/uploads/2019/04/engineer-1-360x360.png'),
        ("Laptop", "Computer portatile in mano, cuffie ed occhiali da lavoro già pronti, questa paperetta è proprio impegnata in una dura giornata di lavoro!", 12.0, 37, 0, 'professioni',
        'https://milanduckstore.com/wp-content/uploads/2019/05/laptop-360x360.png'),
        ("Laureato", "Bachelor Rubber Duck. Summa cum laude o appena passato? Non importa! Fatto è fatto e il diploma è al sicuro in tasca. Regalo perfetto per lo studente che sta per laurearsi.", 12.0, 63, 0, 'professioni',
        'https://milanduckstore.com/wp-content/uploads/2019/04/bachelor-1-360x360.png'),
        ("Laureato D", "Graduate Rubber Acquista l’appassionato studente del Milan Duck Store. Si è appena laureato e non vede l’ora di festeggiare! Per tutti coloro che hanno appena terminato un lungo percorso di studi…", 12.0, 76, 5, 'professioni',
        'https://milanduckstore.com/wp-content/uploads/2019/05/graduate-360x360.png'),
        ("Maestra", "Teacher Duck. La nostra insegnante sembra dura ed inflessibile ma ti affascinerà con tutto il suo sapere!", 12.0, 69, 0, 'professioni',
        'https://milanduckstore.com/wp-content/uploads/2021/02/insegnante1-360x360.png'),
        ("Marinaio", "Sailor Rubber Duck. Acquista la robusta papera di mare del Milan Duck Store. È tornato in città da un lungo viaggio attraverso il mondo. Non c’è un mare troppo in tempesta per lui. O una porta troppo ruvida. Per amici amanti dei sette mari!", 12.0, 83, 10, 'professioni',
        'https://milanduckstore.com/wp-content/uploads/2019/04/sailor-1-360x360.png'),
        ("Muratore", "Bricklayer Rubber Duck.Acquista la papera muratrice del Milan Duck Store. Con i suoi strumenti e il suo cappello sta costruendo un altro bellissimo muro di mattoni. Dalla ad un amico che è in fase di costruzioni!", 12.0, 65, 10, 'professioni',
        'https://milanduckstore.com/wp-content/uploads/2019/04/bricklayer-1-360x360.png'),
        ("Nonna", "Grandma Rubber Duck. Acquista la dolce nonna del Milan Duck Store.Con una tazza di tè, occhiali e vestito rosso.", 12.0, 32, 10, 'professioni',
        'https://milanduckstore.com/wp-content/uploads/2019/04/grandma-360x360.png'),
        ("Nonno", "Granddad Rubber Duck. Compra il dolce nonno del Milan Duck Store. Con bastone da passeggio, occhiali, tuta e papillon.", 12.0, 93, 0, 'professioni',
        'https://milanduckstore.com/wp-content/uploads/2019/04/grandpa-360x360.png'),
        ("Panettiere", "Baker Rubber Duck. Acquista il panettiere paperoso del Milan Duck Store. Con il suo croissant appena sfornato è pronto a portarti la colazione.", 12.0, 78, 10, 'professioni',
        'https://milanduckstore.com/wp-content/uploads/2019/04/baker-1-360x360.png'),
        ("Papera Maglia", "Knitting Duck. La nostra papera che lavora a maglia vi produrrà tutto quello che avrete bisogno per l’inverno: sciarpe, cappelli, golfini e tutto quello che vorrete lei lo realizzerà.", 12.0, 12, 15, 'professioni',
        'https://milanduckstore.com/wp-content/uploads/2022/03/sarta1-360x360.jpeg'),
        ("Paramedico", "Papera Paramedico. La papera Paramedico del Milan Duck Store è pronta per correre in aiuto di tutti coloro che siano in stato di emergenza! Attenti, fateci passare!", 12.0, 33, 5, 'professioni',
        'https://milanduckstore.com/wp-content/uploads/2019/05/paramedic-360x360.png'),
        ("Parrucchiera", "Hair Stylist Duck. Acquista la papera parrucchiera del Milan Duck Store. Con l’asciugacapelli e la spazzola sempre in mano, è pronta per farti la piega o tagliarti le doppie punte.", 12.0, 84, 15, 'professioni',
        'https://milanduckstore.com/wp-content/uploads/2019/05/Parrucchiera1-360x360.jpeg'),
        ("Pilota", "Pilot Rubber Duck. Acquista il primo ufficiale del Milan Duck Store. Vola alto sopra le nuvole. Lontano per destinazioni lontane. Nessun problema. Questa papera di gomma pilota ha il controllo completo. Regalo perfetto per un amico a cui piace viaggiare!", 12.0, 24, 5, 'professioni',
        'https://milanduckstore.com/wp-content/uploads/2019/04/pilot-1-360x360.png'),
        ("Pilota Rosso", "Racer Duck Red. I nostro pilota è pronto a vincere tutte le gare di F1.", 12.0, 87, 15, 'professioni',
        'https://milanduckstore.com/wp-content/uploads/2019/10/DCIG8630-360x360.png'),
        ("Pirata", "Pirate Rubber Duck. Acquista il Jolly Roger del Milan Duck Store. Vaga per la vasca in cerca di tesori e problemi. Dai questa papera pirata a un amico spericolato!", 12.0, 18, 10, 'professioni',
        'https://milanduckstore.com/wp-content/uploads/2019/04/pirate-360x360.png'),
        ("Pirata con Bandiera", "Pirate Rubber Duck with flag. Tutte le mani sul ponte! Questo pirata ha issato la sua bandiera e fa tremare pericolosamente la sua sciabola. Servi un buon rum in fretta, o preparati a camminare sulla tavola …", 12.0, 22, 0, 'professioni',
        'https://milanduckstore.com/wp-content/uploads/2019/04/pirate-with-flag-360x360.png'),
        ("Pizzaman", "Il nostro Pizzaiolo!!", 15.0, 92, 15, 'professioni',
        'https://milanduckstore.com/wp-content/uploads/2023/11/pizzaman1.PNG-360x360.jpg'),
        ("Poliziotto", "Police Duck. Acquista la papera che difende la legge dl Milan Duck Store. Con la pistola ed il manganello, la divisa d’ordinanza ed il tipico cappello, è pronta per entrare in azione.", 12.0, 89, 15, 'professioni',
        'https://milanduckstore.com/wp-content/uploads/2019/05/police-1-360x360.png'),
        ("Pompiere", "Fireman Black rubber duck. Acquista il vigile del fuoco del Milan Duck Store. Un vero eroe. Doma ogni fiammata con la sua manichetta antincendio. Sempre pronto a saltare nel suo camion dei pompieri e correre verso incendi pericolosi. Sorprendi un eroe tra i tuoi amici con questa coraggiosa papera di gomma!", 12.0, 16, 0, 'professioni',
        'https://milanduckstore.com/wp-content/uploads/2019/04/fireman-1-360x360.png'),
        ("Pompiere Rosso", "Questa paperetta a forma di Pompiere è pronta a salvare i tuoi bagnetti da ogni tipo di eventi catastrofico…Per tutti gli amanti di questi eroi metropolitani che ogni giorno ci salvano da pericoli di ogi tipo!", 12.0, 50, 5, 'professioni',
        'https://milanduckstore.com/wp-content/uploads/2019/05/firefighter-360x360.png'),
        ("Rock Star", "Guitar Player Rubber Duck. Acquista l’eroe della chitarra Rock & Roll del Milan Duck Store. Con chitarra elettrica e fascia per capelli stretta sulla fornte. Regalo perfetto per un amico da concerto.", 12.0, 11, 10, 'professioni',
        'https://milanduckstore.com/wp-content/uploads/2019/05/rockstar1-360x360.png'),
        ("Scolara", "School Girl Duck. Lo zainetto è pronto: questa giovane papera scolaretta è pronta per il suo primo giorno di scuola!", 12.0, 79, 10, 'professioni',
        'https://milanduckstore.com/wp-content/uploads/2019/04/school-girl-360x360.png'),
        ("Scolaro", "School Boy Duck. Lo zainetto è pronto: questa giovane papera scolaretta è pronta per il suo primo giorno di scuola!", 12.0, 88, 10, 'professioni',
        'https://milanduckstore.com/wp-content/uploads/2019/04/school-boy-360x360.png'),
        ("Soldier Duck", "Soldier Duck. Con il suo elmetto e la tipica divisa, questa papera ci protegge con coraggio e prudenza da tutti i pericoli del mondo.", 12.0, 86, 10, 'professioni',
        'https://milanduckstore.com/wp-content/uploads/2019/04/soldier-360x360.png'),
        ("Space Duck", "Luxury Space Duck. “Un piccolo passo per una papera, un grande passo la paperosità” Un pianeta non è mai troppo lontano da raggiungere per il nostro Space Duck. Sempre in attesa di una prossima destinazione galattica!", 20.0, 71, 0, 'professioni',
        'https://milanduckstore.com/wp-content/uploads/2019/05/deluxe-spaceduck-360x360.png'),
        ("Subacqueo", "Diver Rubber Duck. Acquista il sommozzatore del Milan Duck Store. Scopre nuove specie nell’oceano o nella tua vasca da bagno. Ottimo da regalare ad un amico che fa immersioni subacquee!", 12.0, 86, 15, 'professioni',
        'https://milanduckstore.com/wp-content/uploads/2019/04/diver-1-360x360.png'),
        ("Tatuatrice", "lo vorreste un altro tatuaggio? La nostra tatuatrice esaudirà ogni vostro desiderio", 12.0, 85, 5, 'professioni',
        'https://milanduckstore.com/wp-content/uploads/2024/12/tatuatrice-360x360.jpg'),
        ("Yoga Duck", "Yoga Rubber Duck.
        Acquista il maestro zen di Milan Duck Store. Il nostro guru con indumento da terzo occhio, catena e yoga. Insegna a tutti il chakra per mantenere le papere in perfetto equilibrio.", 12.0, 21, 15, 'professioni',
        'https://milanduckstore.com/wp-content/uploads/2019/04/yoga-1-360x360.png');