name: tsw

services:
  app:
    build: .
    ports:
      - "127.0.0.1:8080:8080"
    depends_on:
      - mysql
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_PORT=3306
      - MYSQL_DB=DuckDuckStore
      - MYSQL_USER=root
      - MYSQL_PASSWORD=yPtXWCsfUp6QdubYP7ykbdtk
    restart: unless-stopped

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: yPtXWCsfUp6QdubYP7ykbdtk
    ports:
      - "127.0.0.1:3306:3306"
    volumes:
      - ./db.sql:/docker-entrypoint-initdb.d/init.sql
      - mysql_data:/var/lib/mysql
    restart: unless-stopped

volumes:
  mysql_data: 
